name: Staging Server

on:
  push:
    tags:
      - '*'

jobs:
  build-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: asia-east1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build docker image (React Hook Form v2)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=local,src=/tmp/runner-cache
          cache-to: type=local,dest=/tmp/runner-cache,mode=min,compression=zstd
          tags: asia-east1-docker.pkg.dev/develop-server/mezzanine-ui/storybooks/react-hook-form-v2:${{ github.ref_name }}
          build-args: |
            TARGET=mezzanine-ui-react-hook-form-v2

      - name: Build docker image (Admin Components)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=local,src=/tmp/runner-cache
          cache-to: type=local,dest=/tmp/runner-cache,mode=min,compression=zstd
          tags: asia-east1-docker.pkg.dev/develop-server/mezzanine-ui/storybooks/admin-components:${{ github.ref_name }}
          build-args: |
            TARGET=mezzanine-ui-admin-components

      - name: Build docker image (Login Panel)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=local,src=/tmp/runner-cache
          cache-to: type=local,dest=/tmp/runner-cache,mode=min,compression=zstd
          tags: asia-east1-docker.pkg.dev/develop-server/mezzanine-ui/storybooks/login-panel:${{ github.ref_name }}
          build-args: |
            TARGET=mezzanine-ui-login-panel

  update-deployments:
    runs-on: ubuntu-latest
    needs:
      - build-images

    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GAR_JSON_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Update image on GKE'
        run: |-
          gcloud components install kubectl
          gcloud container clusters get-credentials rytass-cluster --region asia-east1 --project develop-server
          kubectl -n mezzanine-ui set image deployments/storybook react-hook-form-v2=asia-east1-docker.pkg.dev/develop-server/mezzanine-ui/storybooks/react-hook-form-v2:${{ github.ref_name }}
          kubectl -n mezzanine-ui set image deployments/storybook admin-components=asia-east1-docker.pkg.dev/develop-server/mezzanine-ui/storybooks/admin-components:${{ github.ref_name }}
          kubectl -n mezzanine-ui set image deployments/storybook login-panel=asia-east1-docker.pkg.dev/develop-server/mezzanine-ui/storybooks/login-panel:${{ github.ref_name }}
